/* â”€â”€ Country data for contact form phone dropdown â”€â”€ */

const PRIORITY_COUNTRY_NAMES = [
  'United States / Canada',
  'United Kingdom',
  'Australia',
  'New Zealand',
  'Germany',
  'Netherlands',
  'United Arab Emirates',
  'Singapore',
];

/* Sorted A-Z. Priority countries appear here too â€” buildCountryDropdown() hoists them. */
const COUNTRY_LIST = [
  { flag: 'ðŸ‡¦ðŸ‡«', name: 'Afghanistan',                       dial: '+93',  rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡±', name: 'Albania',                           dial: '+355', rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡¿', name: 'Algeria',                           dial: '+213', rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡©', name: 'Andorra',                           dial: '+376', rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡´', name: 'Angola',                            dial: '+244', rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡¬', name: 'Antigua and Barbuda',               dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡·', name: 'Argentina',                         dial: '+54',  rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡²', name: 'Armenia',                           dial: '+374', rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡º', name: 'Australia',                         dial: '+61',  rule: 'au'    },
  { flag: 'ðŸ‡¦ðŸ‡¹', name: 'Austria',                           dial: '+43',  rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡¿', name: 'Azerbaijan',                        dial: '+994', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¸', name: 'Bahamas',                           dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡­', name: 'Bahrain',                           dial: '+973', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡©', name: 'Bangladesh',                        dial: '+880', rule: 'bd'    },
  { flag: 'ðŸ‡§ðŸ‡§', name: 'Barbados',                          dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¾', name: 'Belarus',                           dial: '+375', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡ª', name: 'Belgium',                           dial: '+32',  rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¿', name: 'Belize',                            dial: '+501', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¯', name: 'Benin',                             dial: '+229', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¹', name: 'Bhutan',                            dial: '+975', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡´', name: 'Bolivia',                           dial: '+591', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¦', name: 'Bosnia and Herzegovina',            dial: '+387', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¼', name: 'Botswana',                          dial: '+267', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡·', name: 'Brazil',                            dial: '+55',  rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡³', name: 'Brunei',                            dial: '+673', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡¬', name: 'Bulgaria',                          dial: '+359', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡«', name: 'Burkina Faso',                      dial: '+226', rule: 'other' },
  { flag: 'ðŸ‡§ðŸ‡®', name: 'Burundi',                           dial: '+257', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡»', name: 'Cabo Verde',                        dial: '+238', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡­', name: 'Cambodia',                          dial: '+855', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡²', name: 'Cameroon',                          dial: '+237', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡«', name: 'Central African Republic',          dial: '+236', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡©', name: 'Chad',                              dial: '+235', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡±', name: 'Chile',                             dial: '+56',  rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡³', name: 'China',                             dial: '+86',  rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡´', name: 'Colombia',                          dial: '+57',  rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡²', name: 'Comoros',                           dial: '+269', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡¬', name: 'Congo',                             dial: '+242', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡·', name: 'Costa Rica',                        dial: '+506', rule: 'other' },
  { flag: 'ðŸ‡­ðŸ‡·', name: 'Croatia',                           dial: '+385', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡º', name: 'Cuba',                              dial: '+53',  rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡¾', name: 'Cyprus',                            dial: '+357', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡¿', name: 'Czech Republic',                    dial: '+420', rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡©', name: 'DR Congo',                          dial: '+243', rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡°', name: 'Denmark',                           dial: '+45',  rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡¯', name: 'Djibouti',                          dial: '+253', rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡²', name: 'Dominica',                          dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡´', name: 'Dominican Republic',                dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡¨', name: 'Ecuador',                           dial: '+593', rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡¬', name: 'Egypt',                             dial: '+20',  rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡»', name: 'El Salvador',                       dial: '+503', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡¶', name: 'Equatorial Guinea',                 dial: '+240', rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡·', name: 'Eritrea',                           dial: '+291', rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡ª', name: 'Estonia',                           dial: '+372', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¿', name: 'Eswatini',                          dial: '+268', rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡¹', name: 'Ethiopia',                          dial: '+251', rule: 'other' },
  { flag: 'ðŸ‡«ðŸ‡¯', name: 'Fiji',                              dial: '+679', rule: 'other' },
  { flag: 'ðŸ‡«ðŸ‡®', name: 'Finland',                           dial: '+358', rule: 'other' },
  { flag: 'ðŸ‡«ðŸ‡·', name: 'France',                            dial: '+33',  rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡¦', name: 'Gabon',                             dial: '+241', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡²', name: 'Gambia',                            dial: '+220', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡ª', name: 'Georgia',                           dial: '+995', rule: 'other' },
  { flag: 'ðŸ‡©ðŸ‡ª', name: 'Germany',                           dial: '+49',  rule: 'de'    },
  { flag: 'ðŸ‡¬ðŸ‡­', name: 'Ghana',                             dial: '+233', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡·', name: 'Greece',                            dial: '+30',  rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡©', name: 'Grenada',                           dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡¹', name: 'Guatemala',                         dial: '+502', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡³', name: 'Guinea',                            dial: '+224', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡¼', name: 'Guinea-Bissau',                     dial: '+245', rule: 'other' },
  { flag: 'ðŸ‡¬ðŸ‡¾', name: 'Guyana',                            dial: '+592', rule: 'other' },
  { flag: 'ðŸ‡­ðŸ‡¹', name: 'Haiti',                             dial: '+509', rule: 'other' },
  { flag: 'ðŸ‡­ðŸ‡³', name: 'Honduras',                          dial: '+504', rule: 'other' },
  { flag: 'ðŸ‡­ðŸ‡º', name: 'Hungary',                           dial: '+36',  rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡¸', name: 'Iceland',                           dial: '+354', rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡³', name: 'India',                             dial: '+91',  rule: 'in'    },
  { flag: 'ðŸ‡®ðŸ‡©', name: 'Indonesia',                         dial: '+62',  rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡·', name: 'Iran',                              dial: '+98',  rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡¶', name: 'Iraq',                              dial: '+964', rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡ª', name: 'Ireland',                           dial: '+353', rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡±', name: 'Israel',                            dial: '+972', rule: 'other' },
  { flag: 'ðŸ‡®ðŸ‡¹', name: 'Italy',                             dial: '+39',  rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡®', name: 'Ivory Coast',                       dial: '+225', rule: 'other' },
  { flag: 'ðŸ‡¯ðŸ‡²', name: 'Jamaica',                           dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡¯ðŸ‡µ', name: 'Japan',                             dial: '+81',  rule: 'other' },
  { flag: 'ðŸ‡¯ðŸ‡´', name: 'Jordan',                            dial: '+962', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡¿', name: 'Kazakhstan',                        dial: '+7',   rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡ª', name: 'Kenya',                             dial: '+254', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡®', name: 'Kiribati',                          dial: '+686', rule: 'other' },
  { flag: 'ðŸ‡½ðŸ‡°', name: 'Kosovo',                            dial: '+383', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡¼', name: 'Kuwait',                            dial: '+965', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡¬', name: 'Kyrgyzstan',                        dial: '+996', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡¦', name: 'Laos',                              dial: '+856', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡»', name: 'Latvia',                            dial: '+371', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡§', name: 'Lebanon',                           dial: '+961', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡¸', name: 'Lesotho',                           dial: '+266', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡·', name: 'Liberia',                           dial: '+231', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡¾', name: 'Libya',                             dial: '+218', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡®', name: 'Liechtenstein',                     dial: '+423', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡¹', name: 'Lithuania',                         dial: '+370', rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡º', name: 'Luxembourg',                        dial: '+352', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¬', name: 'Madagascar',                        dial: '+261', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¼', name: 'Malawi',                            dial: '+265', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¾', name: 'Malaysia',                          dial: '+60',  rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡»', name: 'Maldives',                          dial: '+960', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡±', name: 'Mali',                              dial: '+223', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¹', name: 'Malta',                             dial: '+356', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡­', name: 'Marshall Islands',                  dial: '+692', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡·', name: 'Mauritania',                        dial: '+222', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡º', name: 'Mauritius',                         dial: '+230', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡½', name: 'Mexico',                            dial: '+52',  rule: 'other' },
  { flag: 'ðŸ‡«ðŸ‡²', name: 'Micronesia',                        dial: '+691', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡©', name: 'Moldova',                           dial: '+373', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¨', name: 'Monaco',                            dial: '+377', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡³', name: 'Mongolia',                          dial: '+976', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡ª', name: 'Montenegro',                        dial: '+382', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¦', name: 'Morocco',                           dial: '+212', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡¿', name: 'Mozambique',                        dial: '+258', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡²', name: 'Myanmar',                           dial: '+95',  rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡¦', name: 'Namibia',                           dial: '+264', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡·', name: 'Nauru',                             dial: '+674', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡µ', name: 'Nepal',                             dial: '+977', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡±', name: 'Netherlands',                       dial: '+31',  rule: 'nl'    },
  { flag: 'ðŸ‡³ðŸ‡¿', name: 'New Zealand',                       dial: '+64',  rule: 'nz'    },
  { flag: 'ðŸ‡³ðŸ‡®', name: 'Nicaragua',                         dial: '+505', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡ª', name: 'Niger',                             dial: '+227', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡¬', name: 'Nigeria',                           dial: '+234', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡µ', name: 'North Korea',                       dial: '+850', rule: 'other' },
  { flag: 'ðŸ‡²ðŸ‡°', name: 'North Macedonia',                   dial: '+389', rule: 'other' },
  { flag: 'ðŸ‡³ðŸ‡´', name: 'Norway',                            dial: '+47',  rule: 'other' },
  { flag: 'ðŸ‡´ðŸ‡²', name: 'Oman',                              dial: '+968', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡°', name: 'Pakistan',                          dial: '+92',  rule: 'pk'    },
  { flag: 'ðŸ‡µðŸ‡¼', name: 'Palau',                             dial: '+680', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡¸', name: 'Palestine',                         dial: '+970', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡¦', name: 'Panama',                            dial: '+507', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡¬', name: 'Papua New Guinea',                  dial: '+675', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡¾', name: 'Paraguay',                          dial: '+595', rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡ª', name: 'Peru',                              dial: '+51',  rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡­', name: 'Philippines',                       dial: '+63',  rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡±', name: 'Poland',                            dial: '+48',  rule: 'other' },
  { flag: 'ðŸ‡µðŸ‡¹', name: 'Portugal',                          dial: '+351', rule: 'other' },
  { flag: 'ðŸ‡¶ðŸ‡¦', name: 'Qatar',                             dial: '+974', rule: 'other' },
  { flag: 'ðŸ‡·ðŸ‡´', name: 'Romania',                           dial: '+40',  rule: 'other' },
  { flag: 'ðŸ‡·ðŸ‡º', name: 'Russia',                            dial: '+7',   rule: 'other' },
  { flag: 'ðŸ‡·ðŸ‡¼', name: 'Rwanda',                            dial: '+250', rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡³', name: 'Saint Kitts and Nevis',             dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡¨', name: 'Saint Lucia',                       dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡»ðŸ‡¨', name: 'Saint Vincent and the Grenadines',  dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡¼ðŸ‡¸', name: 'Samoa',                             dial: '+685', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡²', name: 'San Marino',                        dial: '+378', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¹', name: 'SÃ£o TomÃ© and PrÃ­ncipe',             dial: '+239', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¦', name: 'Saudi Arabia',                      dial: '+966', rule: 'sa'    },
  { flag: 'ðŸ‡¸ðŸ‡³', name: 'Senegal',                           dial: '+221', rule: 'other' },
  { flag: 'ðŸ‡·ðŸ‡¸', name: 'Serbia',                            dial: '+381', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¨', name: 'Seychelles',                        dial: '+248', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡±', name: 'Sierra Leone',                      dial: '+232', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¬', name: 'Singapore',                         dial: '+65',  rule: 'sg'    },
  { flag: 'ðŸ‡¸ðŸ‡°', name: 'Slovakia',                          dial: '+421', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡®', name: 'Slovenia',                          dial: '+386', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡§', name: 'Solomon Islands',                   dial: '+677', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡´', name: 'Somalia',                           dial: '+252', rule: 'other' },
  { flag: 'ðŸ‡¿ðŸ‡¦', name: 'South Africa',                      dial: '+27',  rule: 'other' },
  { flag: 'ðŸ‡°ðŸ‡·', name: 'South Korea',                       dial: '+82',  rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¸', name: 'South Sudan',                       dial: '+211', rule: 'other' },
  { flag: 'ðŸ‡ªðŸ‡¸', name: 'Spain',                             dial: '+34',  rule: 'other' },
  { flag: 'ðŸ‡±ðŸ‡°', name: 'Sri Lanka',                         dial: '+94',  rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡©', name: 'Sudan',                             dial: '+249', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡·', name: 'Suriname',                          dial: '+597', rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡ª', name: 'Sweden',                            dial: '+46',  rule: 'other' },
  { flag: 'ðŸ‡¨ðŸ‡­', name: 'Switzerland',                       dial: '+41',  rule: 'other' },
  { flag: 'ðŸ‡¸ðŸ‡¾', name: 'Syria',                             dial: '+963', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡¼', name: 'Taiwan',                            dial: '+886', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡¯', name: 'Tajikistan',                        dial: '+992', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡¿', name: 'Tanzania',                          dial: '+255', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡­', name: 'Thailand',                          dial: '+66',  rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡±', name: 'Timor-Leste',                       dial: '+670', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡¬', name: 'Togo',                              dial: '+228', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡´', name: 'Tonga',                             dial: '+676', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡¹', name: 'Trinidad and Tobago',               dial: '+1',   rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡³', name: 'Tunisia',                           dial: '+216', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡·', name: 'Turkey',                            dial: '+90',  rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡²', name: 'Turkmenistan',                      dial: '+993', rule: 'other' },
  { flag: 'ðŸ‡¹ðŸ‡»', name: 'Tuvalu',                            dial: '+688', rule: 'other' },
  { flag: 'ðŸ‡ºðŸ‡¬', name: 'Uganda',                            dial: '+256', rule: 'other' },
  { flag: 'ðŸ‡ºðŸ‡¦', name: 'Ukraine',                           dial: '+380', rule: 'other' },
  { flag: 'ðŸ‡¦ðŸ‡ª', name: 'United Arab Emirates',              dial: '+971', rule: 'ae'    },
  { flag: 'ðŸ‡¬ðŸ‡§', name: 'United Kingdom',                    dial: '+44',  rule: 'uk'    },
  { flag: 'ðŸ‡ºðŸ‡¸', name: 'United States / Canada',            dial: '+1',   rule: 'usca'  },
  { flag: 'ðŸ‡ºðŸ‡¾', name: 'Uruguay',                           dial: '+598', rule: 'other' },
  { flag: 'ðŸ‡ºðŸ‡¿', name: 'Uzbekistan',                        dial: '+998', rule: 'other' },
  { flag: 'ðŸ‡»ðŸ‡º', name: 'Vanuatu',                           dial: '+678', rule: 'other' },
  { flag: 'ðŸ‡»ðŸ‡¦', name: 'Vatican City',                      dial: '+39',  rule: 'other' },
  { flag: 'ðŸ‡»ðŸ‡ª', name: 'Venezuela',                         dial: '+58',  rule: 'other' },
  { flag: 'ðŸ‡»ðŸ‡³', name: 'Vietnam',                           dial: '+84',  rule: 'other' },
  { flag: 'ðŸ‡¾ðŸ‡ª', name: 'Yemen',                             dial: '+967', rule: 'other' },
  { flag: 'ðŸ‡¿ðŸ‡²', name: 'Zambia',                            dial: '+260', rule: 'other' },
  { flag: 'ðŸ‡¿ðŸ‡¼', name: 'Zimbabwe',                          dial: '+263', rule: 'other' },
];